name: Entregables

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: paso 1  Checkaout repositorio
        uses: actions/checkout@v4
      - name: paso 2  Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso 3  Crear entorno virtual
        run: python -m venv venv
      - name: paso 4  Activar entorno virtual
        run: ./venv/scripts/activate
      - name: paso 5  Actualizar pip
        run: pip install --upgrade pip
      - name: paso 6  Instalar dependencias
        run: pip install -e .
      - name: paso 7  Ejecutar Script
        run: python src/edu_bigdata/main.py